# Copyright (c) 2022 Purple Clay
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# in the Software without restriction, including without limitation the rights
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

before:
  hooks:
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - id: imds-mock
    ldflags:
      - -s -w
      - -X github.com/purpleclay/imds-mock/cmd.version={{.Tag}}
      - -X github.com/purpleclay/imds-mock/cmd.gitCommit={{.Commit}}
      - -X github.com/purpleclay/imds-mock/cmd.gitBranch=main
      - -X github.com/purpleclay/imds-mock/cmd.buildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - id: imds-mock-archive
    format: tar.gz
    name_template: |-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}
    builds:
      - imds-mock
    replacements:
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^test"
      - "^chore"
      - "^ci"
  groups:
    - title: "Dependency Updates"
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 30
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: "Documentation Updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 40
    - title: "Other Work"
      order: 99

sboms:
  - artifacts: archive

# Use Keyless experimental signing with cosign, see: https://github.com/sigstore/cosign/blob/main/KEYLESS.md
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}"

dockers:
  - image_templates:
      - "purpleclay/imds-mock:{{ .Tag }}-amd64"
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.description=Easy mocking of the Amazon EC2 Instance Metadata Service (IMDS)"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "purpleclay/imds-mock:{{ .Tag }}-arm64"
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.description=Easy mocking of the Amazon EC2 Instance Metadata Service (IMDS)"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "purpleclay/imds-mock:{{ .Tag }}"
    image_templates:
      - "purpleclay/imds-mock:{{ .Tag }}-amd64"
      - "purpleclay/imds-mock:{{ .Tag }}-arm64"
  - name_template: "purpleclay/imds-mock:latest"
    image_templates:
      - "purpleclay/imds-mock:{{ .Tag }}-amd64"
      - "purpleclay/imds-mock:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/purpleclay/imds-mock:{{ .Tag }}"
    image_templates:
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-amd64"
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/purpleclay/imds-mock:latest"
    image_templates:
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-amd64"
      - "ghcr.io/purpleclay/imds-mock:{{ .Tag }}-arm64"

brews:
  - name: imds-mock
    tap:
      owner: purpleclay
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/purpleclay/imds-mock"
    description: "Easy mocking of the Amazon EC2 Instance Metadata Service (IMDS)"
    license: MIT
    install: |
      bin.install "imds-mock"

      bash_output = Utils.safe_popen_read(bin/"imds-mock", "completion", "bash")
      (bash_completion/"imds-mock").write bash_output

      zsh_output = Utils.safe_popen_read(bin/"imds-mock", "completion", "zsh")
      (zsh_completion/"_imds-mock").write zsh_output

      fish_output = Utils.safe_popen_read(bin/"imds-mock", "completion", "fish")
      (fish_completion/"imds-mock.fish").write fish_output

      man1.install "manpages/imds-mock.1.gz"
    test: |
      installed_version = shell_output("#{bin}/imds-mock version --short 2>&1")
      assert_match "v#{version}", installed_version

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: "https://github.com/purpleclay/imds-mock"
    description: "Easy mocking of the Amazon EC2 Instance Metadata Service (IMDS)"
    maintainer: Purple Clay <purpleclaygh@gmail.com>
    license: MIT
    vendor: Purple Clay
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/imds-mock.bash
        dst: /usr/share/bash-completion/completions/imds-mock
        file_info:
          mode: 0644
      - src: ./completions/imds-mock.fish
        dst: /usr/share/fish/completions/imds-mock.fish
        file_info:
          mode: 0644
      - src: ./completions/imds-mock.zsh
        dst: /usr/share/zsh/vendor-completions/_imds-mock
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/imds-mock/copyright
        file_info:
          mode: 0644
      - src: ./manpages/imds-mock.1.gz
        dst: /usr/share/man/man1/imds-mock.1.gz
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids:
      - packages
    env:
      - "FURY_TOKEN={{ .Env.FURY_TOKEN }}"
    cmd: ./scripts/fury-upload.sh {{ .ArtifactName }}

aurs:
  - homepage: "https://github.com/purpleclay/imds-mock"
    description: "Easy mocking of the Amazon EC2 Instance Metadata Service (IMDS)"
    maintainers:
      - "Purple Clay <purple clay at gmail dot com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/imds-mock-bin.git"
    package: |-
      # bin
      install -Dm755 "./imds-mock" "${pkgdir}/usr/bin/imds-mock"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/imds-mock/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/imds-mock.bash" "${pkgdir}/usr/share/bash-completion/completions/imds-mock"
      install -Dm644 "./completions/imds-mock.zsh" "${pkgdir}/usr/share/zsh/site-functions/_imds-mock"
      install -Dm644 "./completions/imds-mock.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/imds-mock.fish"

      # manpages
      install -Dm644 "./manpages/imds-mock.1.gz" "${pkgdir}/usr/share/man/man1/imds-mock.1.gz"

release:
  footer: |
    **Full Changelog**: https://github.com/purpleclay/imds-mock/compare/{{ .PreviousTag }}...{{ .Tag }}

    ## What to do next?

    - Read the [documentation](https://docs.purpleclay.dev/imds-mock/)
    - Follow me on [Twitter](https://twitter.com/purpleclaydev)
    - Read an article on [Medium](https://medium.com/@purpleclay)
